resource "local_file" "pet" {
    filename = var.filename
    content = "my favourite pet is ${random_pet.my-pet.id}"  
}

resource "random_pet" "my-pet" {
    prefix = var.prefix
    separator = var.separator
    length = var.length
  
}

output "pet-name" {
    value = random_pet.my-pet
    description = "record the value of pet ID generated by the random_pet resource"
}


###output varibles

# output "<variable_name>" {
#     value = "<variable_value>"
#     <arguments>
# }